// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class AutoHistory
{
    public int Id { get; set; }

    public string RowId { get; set; }

    public string Kind { get; set; }

    public string TableName { get; set; }

    public string Changed { get; set; }

    public string AffectedColumns { get; set; }

    public string UserId { get; set; }

    public DateTime? Created { get; set; }
}