// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class CertificadosDigitais
{
    public int Id { get; set; }

    public string Certificado_Digital { get; set; }

    public string Senha { get; set; }

    public DateTime Data_Inclusao { get; set; }

    public string Cpf_Cnpj { get; set; }

    public string Login { get; set; }

    public string CN_Certificado { get; set; }

    public string Dados_Certificado { get; set; }

    public virtual ICollection<HistoricoAssinaturas> HistoricoAssinaturas { get; set; } = new List<HistoricoAssinaturas>();
}