// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class Documentos
{
    public int DocumentoID { get; set; }

    public string NomeArquivo { get; set; }

    public string Url { get; set; }

    public DateTime DataInclusao { get; set; }

    public bool? FgAtivo { get; set; }

    public virtual ICollection<Manuais> Manuais { get; set; } = new List<Manuais>();

    public virtual ICollection<Mensagens> Mensagem { get; set; } = new List<Mensagens>();
}