// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class EmployeesDocuments
{
    public int EmployeesDocumentsID { get; set; }

    public int EmployeeID { get; set; }

    public string DocumentName { get; set; }

    public string DocumentPath { get; set; }

    public virtual Employees Employee { get; set; }
}