// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class EquipeTecnica
{
    public int UserID { get; set; }

    public string Nome { get; set; }

    public string SobreNome { get; set; }

    public string EmailPessoal { get; set; }

    public string EmailOrganizacao { get; set; }

    public string Cargo { get; set; }

    public string Celular { get; set; }

    public string LoginID { get; set; }
}