// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class HistoricoAssinaturas
{
    public int Id { get; set; }

    public int Id_Certificado_Digital { get; set; }

    public DateTime Data { get; set; }

    public string Login { get; set; }

    public virtual CertificadosDigitais Id_Certificado_DigitalNavigation { get; set; }
}