// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class Manuais
{
    public int ManualID { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public string Tipo { get; set; }

    public DateTime? DataInclusao { get; set; }

    public bool? FgAtivo { get; set; }

    public int? DocumentoID { get; set; }

    public virtual Documentos Documento { get; set; }
}