// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class Mensagens
{
    public int ID { get; set; }

    public string HistoryID { get; set; }

    public string ParameterSistemaID { get; set; }

    public string Sistema { get; set; }

    public string DeUsuario { get; set; }

    public string ParaUsuario { get; set; }

    public string Perfil { get; set; }

    public string Assunto { get; set; }

    public string Mensagem { get; set; }

    public DateTime? DataInclusao { get; set; }

    public DateTime? DataEnvio { get; set; }

    public DateTime? DataLeitura { get; set; }

    public int TipoMensagensID { get; set; }

    public string MensagensParametros { get; set; }

    public bool? MensagemAlerta { get; set; }

    public bool? StatusMensagem { get; set; }

    public bool? ApresentacaoApp { get; set; }

    public int? QtdDiasApresentacao { get; set; }

    public string EmailsAdicionais { get; set; }

    public DateOnly? DataFim { get; set; }

    public DateOnly? DataInicio { get; set; }

    public int? QtdDiasResposta { get; set; }

    public virtual TipoMensagens TipoMensagens { get; set; }

    public virtual ICollection<Documentos> Documento { get; set; } = new List<Documentos>();
}