// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class NotificacaoDemandante
{
    public int ID { get; set; }

    public string Usuario { get; set; }

    public string Email { get; set; }

    public string Equipe { get; set; }

    public virtual ICollection<Notificacao> Notificacao { get; set; } = new List<Notificacao>();
}