// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class Notificacao
{
    public int ID { get; set; }

    public int DemandanteID { get; set; }

    public int RequerenteID { get; set; }

    public string TipoNotificacao { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public DateTime? Data { get; set; }

    public string Status { get; set; }

    public virtual NotificacaoDemandante Demandante { get; set; }

    public virtual NotificacaoRequerente Requerente { get; set; }
}