// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class RequestResponseLogger
{
    public int LogId { get; set; }

    public string Usuario { get; set; }

    public string Aplicacao { get; set; }

    public DateTime RequestDateTimeUtc { get; set; }

    public DateTime? ResponseDateTimeUtc { get; set; }

    public string ExceptionMessage { get; set; }

    public string ExceptionStackTrace { get; set; }

    public string JsonString { get; set; }

    public int? WorkItemId { get; set; }

    public string WorkItemLink { get; set; }
}