// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class Sistema
{
    public long sis_codigo { get; set; }

    public string sis_nome { get; set; }

    public string sis_descricao { get; set; }

    public bool? sis_requestresponseLogger { get; set; }
}