// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class StudentAdress
{
    public int StudentId { get; set; }

    public int AdressId { get; set; }

    public string Logradouro { get; set; }

    public string Cep { get; set; }

    public string Numero { get; set; }

    public string Cidade { get; set; }

    public virtual Student Student { get; set; }
}