// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Northwind.Data.Northwind.Entity;

public partial class TipoMensagens
{
    public int ID { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<Mensagens> Mensagens { get; set; } = new List<Mensagens>();
}